#!/usr/bin/env ruby -w
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'nag'

class Nag::Monitor < DRbNode
  def start
    read_all_data.group_by {|e| e[1] }.map {|k,v| Hash[k, v.last]}
  end
end

Nag::Monitor.new.start
DRb.thread.join

=begin
loop do
  data = ts.read_all([nil, nil, nil, nil])
  if data.empty?
    puts "No Clients Connected"
  else
    puts "Monitoring Data"
    p data.group_by {|e| e[1] }.map {|k,v| Hash[k, v.last]}
  end
  sleep 2
  system("clear")
end
=end
