#!/usr/bin/env ruby -w
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'nag'
require 'awesome_print'

class Nag::Monitor < DRbNode
  def start
    loop do
      system("clear")
      ap read_all_data.group_by {|e| e[1] }.map {|k,v| Hash[k, v.last.last]}
      sleep 1
    end
  end
end

Nag::Monitor.new.start
